project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

lang: ja

website:
  title: "政治過程論@駒大2026"
  page-footer: 
    right: "@2026 Junpei Suzuki"
  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "シラバス"
        href: 00_syllabus.qmd
      - text: ---
      - section: "イントロダクション（前期）"
        contents:
        - text: "01/前期の導入"
          href: 01_intro_1.qmd
      - section: "政治過程の全体像（前期）"
        contents:
        - text: "02/政治過程の全体像"
          href: 02_pp-overview.qmd
        - text: "03/政治過程と権力"
          href: 03_power.qmd
      - section: "市民・有権者"
        contents:
        - text: "04/市民と政治参加"
          href: 04_participation.qmd
        - text: "05/選挙と投票参加"
          href: 05_election.qmd
        - text: "06/投票行動の理論"
          href: 06_voting.qmd
        - text: "07/選挙制度"
          href: 07_electoralsystem.qmd
      - section: "政党"
        contents:
        - text: "08/政党"
          href: 08_political-party.qmd        
        - text: "09/政党システム"
          href: 09_party-system.qmd   
        - text: "10/政党間競争と協力"
          href: 10_party-competition-cooperation.qmd
      - section: "利益団体"
      - section: "まとめと試験（前期）"
      - text: ---
      - section: "イントロダクション（後期）"
        contents:
        - text: "16/後期の導入"
      - section: "政治過程の全体像（後期）"
      - section: "官僚"
      - section: "制度"
      - section: "隣接分野"
      - section: "まとめと試験（後期）"
      - section: "付録"
        contents:
        - text: "付録01/スライドの保存方法"
          href: app01_pdfexport.qmd        
format:
  html:
    theme: a11y
    grid:
      sidebar-width: 250px
    number-sections: false
    toc: true
    link-external-newwindow: true

freeze: auto

