---
title: "政治過程論"
subtitle: "駒澤大学｜法学部政治学科｜2026年度通年｜木曜日2限"
date: 2026-04-01
date-modified: today
author:
  - name: 鈴木淳平
    affiliation: 駒澤大学法学部政治学科
    email: jsuzuki@komazawa-u.ac.jp
    url: https://junpei-suzuki.github.io
---

::: callout-important
#### 注意

このページは2026年度の駒澤大学法学部政治学科で開講される政治過程論の最新版のシラバスおよび授業資料を兼ねたものです。今後更新していきますが、現時点では未完成です。
:::

## 基礎情報
 - 学期：通年
 - 日時：木曜日2限 (10:40-12:10)
 - 場所：1-203
 - 担当教員：鈴木淳平
     - 所属：法学部政治学科
        - 総合教育研究部の鈴木淳平先生とは別人です
     - 居室：2研2825室（第二研究館8階）
     - オフィスアワー：木曜4限（14:40-16:10）

## 授業概要

政治とは**市民**や**政治家**、**政党**、**利益団体**、**官僚**といった**アクター**（登場人物）が相互に影響しながら織りなすダイナミックな社会現象です。この科目では、そうした現実政治の動きを**理論**と**実証**に基づいて考察できる能力を身につけることを目的とします。政治学の関連する**概念・理論・モデル**を学び、日本そして世界の政治を「印象」ではなく**「根拠」に基づいて分析**できる視座を提供していきます。本科目は主に講義方式によりますが、**アクティブラーニング**を用いたワークを取り入れ、お互いに学び合いながら知識の習得を深めるとともに、政治を考察する経験を積めるよう手助けをしていきます。ただ出席して話を聞くだけでなく積極的な参加が求められますが、こうした経験を通じて**政治学の高度な知識**を得るだけでなく、**市民として政治に正しく向き合う**ことができるようになるでしょう。

**キーワード：**政治過程、アクター、市民、政党、利益団体、官僚、政策過程、制度

## 授業計画

| 回  | 日付 | 部・到達目標       | テーマ                         |
|-----|:-----|:-------------------|:-------------------------------|
| 1   | 4/16  | イントロダクション | [**前期の導入**](01_intro_1.html)                  |
| 2   | 4/23  | 政治過程の全体像 | [**政治過程の全体像** ](02_pp-overview.html)           |
| 3   | 4/30  | 政治過程の全体像   | [**政治過程と権力**](03_power.html)             |
| 4   | 5/7   | 市民・有権者       | [**市民と政治参加**](04_participation.html)             |
| 5   | 5/14  | 市民・有権者       | [**選挙と投票参加**](05_election.html)             |
| 6   | 5/21  | 市民・有権者       | **投票行動の理論**             |
| 7   | 5/28  | 市民・有権者       | **選挙制度**                   |
| 8   | 6/4   | 政党               | **政党**                       |
| 9   | 6/11  | 政党               | **政党システム**               |
| 10  | 6/18  | 政党               | **連立政権**                   |
| 11  | 6/25  | 利益団体           | **利益集団・利益団体**         |
| 12  | 7/2   | 利益団体           | **利益団体の理論**             |
| 13  | 7/9   | 利益団体           | **利益代表の制度**             |
| 14  | 7/16  | まとめと試験       | **前期まとめ**                 |
| 15  | TBD  | まとめと試験       | **期末試験**                   |
| 16  | 9/17  | イントロダクション | **後期の導入**                 |
| 17  | 9/24  | 政治過程の全体像   | **政策過程のモデル**           |
| 18  | 10/1  | 政治過程の全体像   | **課題設定と政策ネットワーク** |
| 19  | 10/8  | 政治過程の全体像   | **メディア**                   |
| 20  | 10/15 | 政治過程の全体像   | **政策過程における組織**       |
| 21  | 10/22 | 官僚               | **官僚と官僚制**               |
| 22  | 10/29 | 官僚               | **政策実施の過程**             |
| 23  | 11/5  | 制度               | **議会制度**                   |
| 24  | 11/12 | 制度               | **執政制度**                   |
| 25  | 11/19 | 制度               | **地方自治制度**               |
| 26  | 11/26 | 隣接分野           | **経済をめぐる政治過程**       |
| 27  | 12/3  | 隣接分野           | **国際関係をめぐる政治過程**   |
| 28  | 12/10 | 隣接分野           | **権威主義をめぐる政治過程**   |
| 29  | 12/17 | まとめと試験       | **後期まとめ**                 |
| 30  | TBD  | まとめと試験          | **学年末試験**                 |
